services:
  web:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    links:
      - app
    depends_on:
      - app
    volumes:
      - ./service/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./service/certs/:/etc/nginx/ssl/:ro
  app:
    image: ddprojects/api
    hostname: api
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./index.php:/var/www/html/index.php:ro
      - ./src/:/var/www/html/src/:ro
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 10
  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: "user"
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      - ./service/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  db-admin:
    image: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: ${DATABASE_SERVER}
    ports:
      - "8000:80"
    links:
      - db
    depends_on:
      - db
volumes:
  db-data: