version: '3'
services:
  app:
    build: ./php
    ports:
      - "8000:8000"
    env_file:
      - ./../.env
    volumes:
      - ./logs/:/tmp/ddLogs/
      - ./products_updates/:/var/www/updates/
      - ./../app/:/var/www/app/
      - ./../web/:/var/www/web/
      - ./../vendor/:/var/www/vendor/
    links:
      - db
    restart: unless-stopped
  db:
    image: postgres:latest
    command: -p ${DATABASE_PORT}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - ./db_data/:/var/lib/postgresql/data/
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: "/var/lib/postgresql/data/pgdata"
  db-web:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: root@ddproj.ru
      PGADMIN_DEFAULT_PASSWORD: ${DATABASE_PASSWORD}
    links:
      - db