services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    links:
      - app
    depends_on:
      - app
    volumes:
      - ./nginx/project.conf:/etc/nginx/conf.d/project.conf:ro
      - ./nginx/certs/:/etc/nginx/ssl/:ro
  app:
    build: php
    env_file:
      - ../.env
    links:
      - db
    depends_on:
      - db
    volumes:
      - ../index.php:/var/www/index.php:ro
      - ../vendor/:/var/www/vendor/:ro
      - ../src/:/var/www/src/:ro
      - ../logs/:/var/www/logs/
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 10
  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: "user"
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      - ./service/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  db-admin:
    image: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - "8080:80"
    links:
      - db
    depends_on:
      - db
volumes:
  db-data: