version: "3.8"
services:
  app:
    build: php
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    env_file:
      - ../.env
    volumes:
      - ../docker/logs/:/tmp/ddLogs/
      - ../docker/products_updates/:/var/www/updates/
      - ../app/:/var/www/app/
      - ../web/:/var/www/web/
      - ../vendor/:/var/www/vendor/
    # UNCOMMENT ONLY FOR LOCAL DEVELOPMENT
    #links:
    #  - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 10
  # UNCOMMENT ONLY FOR LOCAL DEVELOPMENT
  #db:
  #  image: mysql:latest
  #  command: -P ${DATABASE_PORT}
  #  environment:
  #    MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
  #    MYSQL_DATABASE: ${DATABASE_NAME}
  #    MYSQL_USER: ${DATABASE_USER}
  #    MYSQL_PASSWORD: ${DATABASE_PASSWORD}
  #  ports:
  #    - "${DATABASE_PORT}:${DATABASE_PORT}"
  #  volumes:
  #    - ./database/data/:/var/lib/mysql